name: Collect_tests

on: 
  push:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running tests
      id: tests
      run: |
          docker network create siged_backend && docker-compose run api_clients bash -c  "yarn && yarn jest --coverage --forceExit"
    - name: collect
      id: metrics
      run: |
        pip3 install xmltodict
        python3 parser.py fga-eps-mds_${{ github.event.repository.name }}
